###################################################
# Azure Data sources config
###################################################
dataSourceConfigs:
  - className: org.apache.pinot.thirdeye.datasource.pinot.PinotThirdEyeDataSource
    properties:
      zookeeperUrl: pinot-live-zookeeper-headless.pinot-live.svc.cluster.local:2181
      clusterName: pinot-quickstart
      controllerConnectionScheme: http
      controllerHost: pinot-live-controller-headless.pinot-live.svc.cluster.local
      controllerPort: 9000
      cacheLoaderClassName: org.apache.pinot.thirdeye.datasource.pinot.PinotControllerResponseCacheLoader
    metadataSourceConfigs:
      - className: org.apache.pinot.thirdeye.auto.onboard.AutoOnboardPinotMetadataSource
